from app.alimento import Alimento
from app.principal import Principal
from app.bebida import Bebida
from app.postre import Postre
from app.acompaniamiento import Acompaniamiento
from app.proteina import Proteina
from app.carne import Carne
from app.pollo import Pollo
from app.sopa import Sopa
from app.ensalada import Ensalada
from app.menu import Menu
